FROM python:3.6.6

# install environment dependencies
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

# set the working directory
RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add entrypoint
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app

# run the server
CMD ["/usr/src/app/entrypoint.sh"]
